version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: production
    env_file: 
      - ./.env.dev
  redis:
    image: "redis:alpine"