"""empty message

Revision ID: 438c74026165
Revises: 7f7a61d6962c
Create Date: 2020-03-10 19:48:36.706958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438c74026165'
down_revision = '7f7a61d6962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
